import type { Metadata } from "next";
import { Quintessential } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import NewsletterSignup from "@/components/NewsletterSignup";
import { Analytics } from "@vercel/analytics/next";

const quintessential = Quintessential({
  variable: "--font-quintessential",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quintessential.variable}>
      <body
        className={`font-sans antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <NewsletterSignup />
        <Analytics />
      </body>
    </html>
  );
}
